server:
  port: 9001
logging:
  config: classpath:logback.xml
spring:
  aop:
    proxy-target-class: true
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://120.77.221.218:13306/scj_crm?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 5
      max-active: 10
      min-idle: 5
      filter:
        stat:
          log-slow-sql: true
          db-type: mysql
          enabled: true
  application:
    name: scj-building-backend
  cloud:
    nacos:
      discovery:
        server-addr: 120.77.221.218:8848 #nacos控制台地址
        enabled: true #是否启用服务发现，不选默认启用
    sentinel:
      transport:
        dashboard: 120.77.221.218:8858 #sentinel 控制台地址
        port: 8888 #此端口和sentinel通信端口
feign:
  sentinel:
    enabled: true #sentinel 对feign的支持开关
